SELECT 
        ISNULL(VENDIDO.TOT, 0) AS VENDIDO,
        ISNULL(ALUGADO.TOT, 0) AS ALUGADO,
        ISNULL(RESERVADO.TOT, 0) AS RESERVADO,
        ISNULL(COMERCIAL.TOT, 0) AS COMERCIAL,
        ISNULL(DISPONIVEL.TOT, 0) AS DISPONIVEL,
        ISNULL(PERMUTA.TOT, 0) AS PERMUTA
    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XSU
    LEFT OUTER JOIN [srvbd].CorporeRM.dbo.XALGIMOVEL XALGIMOVEL(NOLOCK) 
        ON (XALGIMOVEL.CODIMOVEL = XSU.CODIMOVEL
            AND XALGIMOVEL.CODCOLIMOVEL = XSU.CODCOLIMOVEL)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    WHERE XU.COD_SIT_SUB_UNID IN ('900') 
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) VENDIDO
        ON (VENDIDO.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND VENDIDO.NUM_UNID = XSU.NUM_UNID)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    LEFT OUTER JOIN [srvbd].CorporeRM.dbo.XALGIMOVEL XALGIMOVEL(NOLOCK) 
                        ON (XALGIMOVEL.CODIMOVEL = XU.CODIMOVEL
                            AND XALGIMOVEL.CODCOLIMOVEL = XU.CODCOLIMOVEL)
                    WHERE (XU.COD_SIT_SUB_UNID IN ('151', '901') OR XU.STATUSALUGUEL IN ('151', '901')  
                        OR ISNULL(XALGIMOVEL.SITUACAOIMOVEL, 1) IN ('2'))
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) ALUGADO
        ON (ALUGADO.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND ALUGADO.NUM_UNID = XSU.NUM_UNID)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    LEFT OUTER JOIN [srvbd].CorporeRM.dbo.XALGIMOVEL XALGIMOVEL(NOLOCK) 
                        ON (XALGIMOVEL.CODIMOVEL = XU.CODIMOVEL
                            AND XALGIMOVEL.CODCOLIMOVEL = XU.CODCOLIMOVEL)
                    WHERE (XU.COD_SIT_SUB_UNID IN ('200', '201') OR XU.STATUSALUGUEL IN ('200', '201') 
                        OR ISNULL(XALGIMOVEL.SITUACAOIMOVEL, 1) IN ('5'))
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) RESERVADO
        ON (RESERVADO.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND RESERVADO.NUM_UNID = XSU.NUM_UNID)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    WHERE XU.COD_SIT_SUB_UNID IN ('902')
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) PERMUTA
        ON (PERMUTA.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND PERMUTA.NUM_UNID = XSU.NUM_UNID)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    LEFT OUTER JOIN [srvbd].CorporeRM.dbo.XALGIMOVEL XALGIMOVEL(NOLOCK) 
                        ON (XALGIMOVEL.CODIMOVEL = XU.CODIMOVEL
                            AND XALGIMOVEL.CODCOLIMOVEL = XU.CODCOLIMOVEL)
                    WHERE (XU.COD_SIT_SUB_UNID IN ('903')  
                        AND XU.STATUSALUGUEL NOT IN ('151', '901') 
                        AND ISNULL(XALGIMOVEL.SITUACAOIMOVEL, 1) NOT IN ('2'))
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) COMERCIAL
        ON (COMERCIAL.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND COMERCIAL.NUM_UNID = XSU.NUM_UNID)
    LEFT OUTER JOIN (SELECT COUNT(XU.NUM_SUB_UNID) AS TOT, XU.COD_PESS_EMPR, XU.NUM_UNID
                    FROM [srvbd].CorporeRM.dbo.XSUBUNIDADE XU
                    LEFT OUTER JOIN [srvbd].CorporeRM.dbo.XALGIMOVEL XALGIMOVEL(NOLOCK) 
                        ON (XALGIMOVEL.CODIMOVEL = XU.CODIMOVEL
                            AND XALGIMOVEL.CODCOLIMOVEL = XU.CODCOLIMOVEL)
                    WHERE ISNUMERIC(XU.NUM_SUB_UNID) = 1 
                        AND XU.COD_SIT_SUB_UNID IN ('100') 
                        AND ISNULL(XU.STATUSALUGUEL, '101') NOT IN ('151', '901') 
                        AND ISNULL(XALGIMOVEL.SITUACAOIMOVEL, 1) NOT IN ('2', '5')
                        AND XU.COD_PESS_EMPR = '17'
                        AND REPLACE(XU.NUM_UNID, ' ', '') = 'TOR 3'
                    GROUP BY XU.COD_PESS_EMPR, XU.NUM_UNID) DISPONIVEL
        ON (DISPONIVEL.COD_PESS_EMPR = XSU.COD_PESS_EMPR
            AND DISPONIVEL.NUM_UNID = XSU.NUM_UNID)
    WHERE ISNUMERIC(XSU.NUM_SUB_UNID) = 1
        AND XSU.NUM_SUB_UNID > '0' AND XSU.NUM_SUB_UNID < '99999'
        AND XSU.COD_PESS_EMPR = '17'
        AND REPLACE(XSU.NUM_UNID, ' ', '') = 'TOR 3'
    GROUP BY XSU.COD_PESS_EMPR, XSU.NUM_UNID, VENDIDO.TOT, ALUGADO.TOT, RESERVADO.TOT, COMERCIAL.TOT, DISPONIVEL.TOT, PERMUTA.TOT